service: ssifwc-api

provider:
  name: aws
  region: us-east-1
  runtime: python3.6

functions:
  api:
    handler: ssifwc.handler.endpoint
    name: api
    events:
      - http:
          path: watersheds
          method: get
          cors: true
      - http:
          path: epicollect
          method: get
          cors: true
      - http:
          path: epicollect
          method: post
          cors: true
      - http:
          path: image
          method: post
          cors: true
      - http:
          path: aquifers
          method: get
          cors: true
      - http:
          path: culverts
          method: get
          cors: true
      - http:
          path: faults
          method: get
          cors: true
      - http:
          path: greenwood
          method: get
          cors: true
    environment:
      DATABASE_CONNECTION_URI: ${file(./serverless.env.yml):${self:provider.stage}.DATABASE_CONNECTION_URI}
      EPICOLLECT_BASE_URL: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_BASE_URL}
      EPICOLLECT_PROJECT_NAME: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_PROJECT_NAME}
      EPICOLLECT_CLIENT_ID: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_CLIENT_ID}
      EPICOLLECT_CLIENT_SECRET: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_CLIENT_SECRET}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
