service: ssifwc-api

provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  timeout: 30

functions:
  api:
    handler: ssifwc.handler.endpoint
    name: api
    events:
      - http:
          path: watersheds
          method: get
          cors: true
      - http:
          path: wells
          method: get
          cors: true
      - http:
          path: parcels
          method: get
          cors: true
      - http:
          path: springs
          method: get
          cors: true
      - http:
          path: epicollect
          method: get
          cors: true
      - http:
          path: epicollect
          method: post
          cors: true
      - http:
          path: image
          method: post
          cors: true
      - http:
          path: aquifers
          method: get
          cors: true
      - http:
          path: culverts
          method: get
          cors: true
      - http:
          path: faults
          method: get
          cors: true
      - http:
          path: greenwood
          method: get
          cors: true
      - http:
          path: metrics
          method: post
          cors: true
    environment:
      DATABASE_CONNECTION_URI: ${file(./serverless.env.yml):${self:provider.stage}.DATABASE_CONNECTION_URI}
      EPICOLLECT_BASE_URL: ${file(./serverless.env.yml):${self:provider.stage}.EPICOLLECT_BASE_URL}

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
